//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Razom.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getResponse", ReplyAction="http://tempuri.org/IService1/getResponseResponse")]
        string getResponse();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getResponse", ReplyAction="http://tempuri.org/IService1/getResponseResponse")]
        System.Threading.Tasks.Task<string> getResponseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/runParce", ReplyAction="http://tempuri.org/IService1/runParceResponse")]
        void runParce();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/runParce", ReplyAction="http://tempuri.org/IService1/runParceResponse")]
        System.Threading.Tasks.Task runParceAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Razom.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Razom.ServiceReference1.IService1>, Razom.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getResponse() {
            return base.Channel.getResponse();
        }
        
        public System.Threading.Tasks.Task<string> getResponseAsync() {
            return base.Channel.getResponseAsync();
        }
        
        public void runParce() {
            base.Channel.runParce();
        }
        
        public System.Threading.Tasks.Task runParceAsync() {
            return base.Channel.runParceAsync();
        }
    }
}
