//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_9B1096_razomEntities : DbContext
    {
        public DB_9B1096_razomEntities()
            : base("name=DB_9B1096_razomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Comments> Comments { get; set; }
        public DbSet<DataType> DataType { get; set; }
        public DbSet<FuturePlace> FuturePlace { get; set; }
        public DbSet<History> History { get; set; }
        public DbSet<Invite> Invite { get; set; }
        public DbSet<Issues> Issues { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<Network> Network { get; set; }
        public DbSet<NetworkAccounts> NetworkAccounts { get; set; }
        public DbSet<PhotosPlace> PhotosPlace { get; set; }
        public DbSet<Places> Places { get; set; }
        public DbSet<PlaceType> PlaceType { get; set; }
        public DbSet<Region> Region { get; set; }
        public DbSet<Tag> Tag { get; set; }
        public DbSet<TagToPlace> TagToPlace { get; set; }
        public DbSet<Test> Test { get; set; }
        public DbSet<TestData> TestData { get; set; }
        public DbSet<TestType> TestType { get; set; }
        public DbSet<TravelPlaces> TravelPlaces { get; set; }
        public DbSet<Travels> Travels { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UsersData> UsersData { get; set; }
    }
}
