//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public Places()
        {
            this.Comments = new HashSet<Comments>();
            this.FuturePlace = new HashSet<FuturePlace>();
            this.PhotosPlace = new HashSet<PhotosPlace>();
            this.TravelPlaces = new HashSet<TravelPlaces>();
        }
    
        public int PlaceID { get; set; }
        public Nullable<int> PlaceTypeID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Coordinates { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual ICollection<FuturePlace> FuturePlace { get; set; }
        public virtual ICollection<PhotosPlace> PhotosPlace { get; set; }
        public virtual Region Region { get; set; }
        public virtual PlaceType PlaceType { get; set; }
        public virtual TagToPlace TagToPlace { get; set; }
        public virtual ICollection<TravelPlaces> TravelPlaces { get; set; }
    }
}
