//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagToPlace
    {
        public int Id { get; set; }
        public Nullable<int> PlaceID { get; set; }
        public Nullable<int> TagID { get; set; }
    
        public virtual Places Places { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
