//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestData
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Data { get; set; }
        public Nullable<int> QuestionID { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual Users Users { get; set; }
    }
}
