//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travels
    {
        public Travels()
        {
            this.History = new HashSet<History>();
            this.Message = new HashSet<Message>();
            this.TravelPlaces = new HashSet<TravelPlaces>();
        }
    
        public int TravelID { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<History> History { get; set; }
        public virtual Invite Invite { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<TravelPlaces> TravelPlaces { get; set; }
    }
}
