//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersData
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> NetworkID { get; set; }
        public Nullable<int> DataTypeID { get; set; }
        public string Data { get; set; }
    
        public virtual DataType DataType { get; set; }
        public virtual Network Network { get; set; }
        public virtual Users Users { get; set; }
    }
}
